'''
Usage
------
To run a specific random seed
$ snakemake --config scenario=1 random_seed=101 --profile ../../profiles/hugheslab_cluster/ single_simulation_following_template

To run with multiple random seeds (prespecified in a config file)
$ snakemake --config scenario=2 --profile ../../profiles/hugheslab_cluster/ many_simulations_following_template

Prerequisites
-------------
1) Need local install of anaconda
2) Need local install of Snakemake
See README.md for install instructions
'''
import itertools
import glob
import os
import numpy as np

REPO_ROOT_DIR = os.environ.get("REPO_ROOT_DIR", "/cluster/tufts/hugheslab/code/covid19-forecasting/")
os.environ['REPO_ROOT_DIR'] = os.path.abspath(REPO_ROOT_DIR)

# Specified in configfile:
# --scenario {1,2,3,4}
# --output_dir
# --min_random_seed 1001
# --max_random_seed 1100
# --random_seed 1001
configfile: "config.json"

rule plot:
    input:
        input_files=[os.path.join(
                os.path.expandvars(config['output_dir']),
                "summary-percentile={percentile:06.2f}.csv".format(
                    percentile=float(perc))
                )
            for perc in config['comma_sep_percentiles'].split(',')],
        plot_script=os.path.join(REPO_ROOT_DIR, 'plot', 'plot.py'),
        source_files=glob.glob(os.path.join(REPO_ROOT_DIR, 'plot', '*.py'))

    output:
        html_file=os.path.join(os.path.expandvars(config['output_dir']), "dashboard.html")

    shell:
        """\
        pushd ../../plot/ && python {{input.plot_script}} \
            --dash False \
            --output_html_file "{{output.html_file}}" \
            --output_path "{output_dir}" \
        """.format(output_dir=os.path.expandvars(config['output_dir']))

rule summarize:
    input:
        summarize_script=os.path.join(REPO_ROOT_DIR, 'summarize_forecasts.py'),
        source_files=glob.glob(os.path.join(REPO_ROOT_DIR, 'semimarkov_forecaster/*.py'))

    output:
        [os.path.join(
                os.path.expandvars(config['output_dir']),
                "summary-percentile={percentile:06.2f}.csv".format(percentile=float(perc))
                )
            for perc in config['comma_sep_percentiles'].split(',')]

    conda:
        os.path.join(REPO_ROOT_DIR, "semimarkov_forecaster.yml")

    shell:
        """
        python {{input.summarize_script}}
            --comma_sep_percentiles "{perc}"
            --input_dir "{input_dir}" \
            --output_dir "{input_dir}" \
        """.format(
            perc=config['comma_sep_percentiles'],
            input_dir=os.path.expandvars(config['output_dir']))

# Target rule to run multiple simulations saved to different CSV files
#
# Uses the 'template' defined below
rule many_simulations_following_template:
    input:
        [os.path.join(
                os.path.expandvars(config['output_dir']),          
                "scenario{scenario}".format(scenario=scenario),
                "results-random_seed={random_seed}.csv".format(random_seed=seed)
                )
            for scenario, seed in itertools.product(
                config['comma_sep_scenarios'].split(','),
                range(config['min_random_seed'], config['max_random_seed']))]


# Target rule to run one specific simulation (with seed provided by manual command line input)
#
# Uses the 'template' defined below
rule single_simulation_following_template:
    input:
        os.path.join(
            os.path.expandvars(config['output_dir']),
            "scenario{scenario}".format(scenario=config['scenario']),
            "results-random_seed={random_seed}.csv".format(random_seed=config['random_seed']),
            )

rule template:
    input:
        params_json="params.json",
        script=glob.glob(os.path.join(REPO_ROOT_DIR, 'run_forecast.py')),
        source_files=glob.glob(os.path.join(REPO_ROOT_DIR, 'semimarkov_forecaster/*.py'))

    output:
        output_csv=os.path.join(
            os.path.expandvars("{output_dir}"),
            "scenario{scenario}",
            "results-random_seed={random_seed}.csv")

    conda:
        "semimarkov_forecaster.yml"

    shell:
        """\
        dirname {output.output_csv} | xargs mkdir -p && \
        python {input.script} \
            --config_file "{input.params_json}" \
            --random_seed "{wildcards.random_seed}" \
            --output_file "{output.output_csv}" \
            --scenario "{wildcards.scenario}" \
            --num_seeds %s \
        """ % (config['num_seeds_per_run'])

