name: tf_covid_env
channels:
  - defaults
dependencies:
  - python=3.7.11
  - pandas=1.3.2
  - scipy=1.7.1
  - pip:
    - keras==2.6.0
    - numpy==1.19.5
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.0
    - tensorflow-estimator==2.6.0
    - tensorflow-probability==0.13.0
